---
framework: jasmine
blocklist:
 - "spec/unit/calculator.class.spec.js##Calculator Class"
preMerge:
  pattern:
    - "spec/**/*.js"
postMerge:
  pattern:
    - "spec/**/*.js"
preRun: 
  command: 
    - npm ci    
postRun:
  command: 
    - echo 'Done Testing'
parallelism : 4
version: 1.0
