---
framework: jasmine
preRun: 
  command: 
    - npm ci   
preMerge:
  pattern:
    - "spec/**/*.spec.js"
postMerge:
  pattern:
    - "spec/**/*.spec.js"
postRun:
  command: 
    - echo 'Done Testing'
version: 1.0
